name: Run Python Mail Script
on:
  workflow_dispatch:

jobs:
  send_mail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install smtplib email-validator

      - name: Run mail script
        run: python mail.py
